### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by kkamel** [kpister/spam#3]
https://github.com/kpister/spam/blob/dfa06f7d0a8b1bd60c6af29e05666afc316c28fc/crypto/crypto.go#L14

**Comment by streddy** [comment]
i think that's setting the exponent

**Comment by kpister** [comment]
Could be done better, but we need to have a global variable "e" which represents the public exponent. This will be the same for all nodes because they all use 2048 bits for the key generation. See keygen and RSA alg

**Comment by kpister** [comment]
https://golang.org/pkg/math/big/#Float.SetInt
